### PR TITLE
Add new bounded NLS test: COVID19 regression of São Paulo, Brazil

### PR DESCRIPTION
**Pull request by abelsiqueira**
The model defined as `beta[3] / (1 + exp(-beta[1] - beta[2] * x))` was producing NaN on the derivatives, that's why it was failing.

### CODE REVIEW

**Comment by dpo** [comment]
The NaNs were due to the starting point?

**Comment by abelsiqueira** [comment]
No, after one iteration, the point was large-ish, but the derivative was NaN.

**Comment by dpo** [comment]
Great that TRON solves the problem!

**Comment by dpo** [comment]
I'm not sure how to make that first test pass.

**Comment by dpo** [comment]
What did you change?

**Comment by abelsiqueira** [comment]
The lower bound of Julia :)
The new NLPModels bounds Julia >= 1.3.

**Pull request merged**
