### PR TITLE
WIP: Expose parameters for lbfgs with NamedTuples

### PR DESCRIPTION
**Pull request by MonssafToukal**
I have been working on tuning `lbfgs` for some time using NamedTuples to expose parameters. There might be a more efficient way to do it, but this seems to work for now. Basically, after the parameters are exposed, they are tuned using two other modules: `BBModels.jl` and `SolverTuning.jl`. An example for the tuning process can be found here: https://github.com/ProofOfConceptForJuliSmoothOptimizers/JSOSolvers.jl/blob/lbfgs-tuning/tuning/tune.jl

An example of what the end-to-end tuning process would look like: https://github.com/ProofOfConceptForJuliSmoothOptimizers/JSOSolvers.jl/pull/12

### CODE REVIEW

**Comment by dpo** [comment]
I'd like to discuss how this relates to what @abelsiqueira proposed in https://github.com/JuliaSmoothOptimizers/SolverCore.jl/pull/6/files#diff-29422ba68eda9e9c1fcd2f81939ea4429dc1dcf42ad93f199320ce99c222e5e8. Some of this stuff should go into SolverCore.

**Review by abelsiqueira — CHANGES_REQUESTED** [review]
Thanks for the PR. I left some comments and here are some first impressions:

- I like the idea of the solver holdings its own parameters.
- There is no parameter information, e.g., valid values and ranges. This seems like something that should be informed here.
- Tests are failing.

Maybe we should update SolverCore with a fake solver first and create a working example there?

**Comment by MonssafToukal** [comment]
We could also use a structure like this one for the parameters: https://github.com/MonssafToukal/SolverParameters.jl/blob/main/src/parameters.jl

Each parameter would have a domain that could be defined like this: https://github.com/MonssafToukal/SolverParameters.jl/blob/main/src/domains.jl

What do you think @abelsiqueira ?

**Comment by abelsiqueira** [comment]
Looks like a good idea to me, @MonssafToukal.

**Pull request closed without merging**
