### PR TITLE
Trunk for quasi-Newton models

### PR DESCRIPTION
**Pull request by dpo**
Benchmark script: https://gist.github.com/4c1c74974a59d58ce91c8a513ebdbc54

Results on the 57 unconstrained problems from OptimizationProblems with nvar ≥ 100:

trunkqn

LSR1 very disappointing. Something is off because Trunk appears to do fewer hprods than LBFGS and LSR1 (which do not perform any of course)?!?!?!

### CODE REVIEW

**Comment by dpo** [comment]
I suspect it's the fact that measures that are zero in the profiles are shifted to 1.

**Comment by abelsiqueira** [comment]
Shouldn't all measures be shifted by 1, if any are 0?

**Comment by dpo** [comment]
Good point. I don't think that's what we do.

**Comment by abelsiqueira** [comment]
Only noticed the edit now, and came to write the same thing. Apparently the graph is right, only the robustness is driving things down. Do you think it can be improved or should we merge?

**Comment by dpo** [comment]
I'm double-checking the LSR1 linear operator.

**Comment by dpo** [comment]
I didn't find bugs in the L-SR1 operator. I guess it just sucks ;-).

**Pull request merged**
