### PR TITLE
Update JSOSolvers for Krylov 0.8

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@abelsiqueira @tmigot 
Do you want to keep Julia 1.3 ?
Krylov.jl only work for Julia >= 1.6 now.

**Comment by tmigot** [comment]
> @abelsiqueira @tmigot Do you want to keep Julia 1.3 ? Krylov.jl only works for Julia >= 1.6 now.

Hi @amontoison, thanks for this PR.
Can you make a separate PR dropping Julia 1.3?

**Review by tmigot — APPROVED** [review]
Thanks!

**Comment by abelsiqueira** [comment]
Thank you

**Pull request merged**
