### PR TITLE
TRON for nonlinear least squares

### PR DESCRIPTION
**Pull request by abelsiqueira**
Just the tests for now.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Mostly the same as TRON, but instead of a second-order quadratic approximation to `|F(x)|^2 / 2`, we use the approximation `|J(x)s + F(x)|^2 / 2`.

**Comment by dpo** [comment]
Could you rebase this?

**Comment by abelsiqueira** [comment]
Rebased and changed to use `Val`, like `trunk`.

**Comment by dpo** [comment]
Thank you! Would be good to have your NLS model to debug that trust-region error we saw tonight.

**Pull request merged**
